# Generated by Django 5.2.7 on 2025-11-10 17:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cccd', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('plate_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('status', models.CharField(default='valid', max_length=10)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('term', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('duration', models.IntegerField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, editable=False, null=True)),
                ('cccd', models.OneToOneField(db_column='cccd', on_delete=django.db.models.deletion.CASCADE, to='Accounts.customer')),
            ],
        ),
    ]
