# Generated by Django 5.2.7 on 2025-11-02 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('disable', 'Disabled')], db_column='status', default='inactive', max_length=10)),
            ],
            options={
                'db_table': 'Parkings_card',
            },
        ),
        migrations.CreateModel(
            name='ParkingRecord',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('plate_number', models.CharField(db_column='plate_number', max_length=20)),
                ('vehicle_type', models.CharField(choices=[('motorbike', 'Motorbike'), ('car', 'Car')], db_column='vehicle_type', max_length=20)),
                ('check_in_time', models.DateTimeField(auto_now_add=True, db_column='check_in_time')),
                ('check_out_time', models.DateTimeField(blank=True, db_column='check_out_time', null=True)),
                ('image_path', models.CharField(blank=True, db_column='image_path', max_length=255, null=True)),
                ('card', models.ForeignKey(db_column='card_id', on_delete=django.db.models.deletion.CASCADE, to='Parkings.card')),
            ],
            options={
                'db_table': 'Parkings_parkingrecord',
            },
        ),
    ]
