# Generated by Django 4.2.11 on 2025-11-02 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_code', models.CharField(max_length=20, unique=True)),
                ('slot_type', models.CharField(default='car', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_records', to='Parkings.card')),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_records', to='Parkings.parkingslot')),
            ],
        ),
    ]
