# Generated by Django 5.2.7 on 2025-11-07 02:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
       ('Parkings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('pricing_id', models.CharField(default='1', max_length=50, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('motorbike', 'Motorbike'), ('car', 'Car')], max_length=20)),
                ('term', models.CharField(choices=[('hourly', 'Hourly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingInvoice',
            fields=[
                ('invoice_id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parkings.parkingrecord')),
                ('pricing', models.ForeignKey(blank=True, db_column='pricing_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Billings.pricing')),
            ],
        ),
        migrations.CreateModel(
            name='ContractInvoice',
            fields=[
                ('invoice_id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pricing_id', models.ForeignKey(db_column='pricing_id', on_delete=django.db.models.deletion.CASCADE, to='Billings.pricing')),
            ],
        ),
    ]
