# Generated by Django 5.2.7 on 2025-11-07 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Billings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='term',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='vehicle_type',
        ),
    ]
