# Generated by Django 5.2.7 on 2025-11-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billings', '0002_remove_pricing_term_remove_pricing_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='term',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='pricing',
            name='vehicle_type',
            field=models.CharField(choices=[('motorbike', 'Motorbike'), ('car', 'Car')], default='motorbike', max_length=100),
        ),
    ]
