# Generated by Django 4.2.11 on 2025-11-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billings', '0003_pricing_term_pricing_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
